services:
  wayward-server:
    image: wayward:latest
    container_name: wayward-server
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - STEAM_USER=${STEAM_USER}
      - STEAM_PASS=${STEAM_PASS}
      - load=${SAVE_NAME}
    ports:
      - 38740:38740
    volumes:
      - ${LOCAL_PATH}/server:/home/steam/wayward-server
      - ${LOCAL_PATH}/saves:/home/steam/save
      - ${LOCAL_PATH}/steamcache:/home/steam/Steam
