services:
  wayward-server:
    image: samuelt1/wayward:latest
    container_name: wayward-server
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - STEAM_USER=${STEAM_USER}
      - STEAM_PASS=${STEAM_PASS}
      - load=${SAVE_NAME}
    ports:
      - 38740:38740
    volumes:
      - ${LOCAL_PATH}:/home/steam/data
